#+SETUPFILE: template.org
* *Gabriel Marin*
#+BEGIN_CENTER
[[mailto:marin.gabriel@protonmail.com][marin.gabriel@protonmail.com]] |
[[https://github.com/gbrlmarn][github.com/gbrlmarn]] |
[[https://linkedin.com/in/maringabriel][linkedin.com/in/maringabriel]]
#+END_CENTER
** *Skills*
Programming Languages: C, C++, Clojure, Go, Java, Lisp, Rust,
Bash, HTML, CSS, LaTeX, Erlang, Elixir, C#, SQL, NoSQL, Datomic\\
Tools: Linux, Git, Emacs, Coreutils, Docker, Boost, Vim, ZeroMQ,
RabbitMQ, Django, Hugo, React
** *Work Experience*
*** *Luxoft*, Software Engineer \hfill 2022 -- Present
- Provided better testing tooling to at least 2 other teams by developing command line
  application using C++ and ZeroMQ library for sending/receiving messages over TCP sockets.
- Increase code coverage by minimum 75% by creating unit tests using Boost library.
- Aligned codebase in 5 projects according to coding guidelines
  by refactoring multiple repositories.
*** *Continental*, Software Engineer \hfill 2021 -- 2022
- Enhanced C code production by working on XML generator using Java and AUTOSAR library.
*** *Ministry of Internal Affairs*, System Engineer \hfill 2019 -- 2021
- Reduce software install time by more than 1 hour on a new PC by creating automation scripts.
*** *Ministry of Internal Affairs*, Middleware Engineer \hfill 2018 -- 2019
- Give access to at least 80 users in Oracle SQL database by changing permissions according
  to requirements.
** *Open Source Experience*
*** *Curl* \hfill [[https://github.com/curl/curl][curl]]
- Improved code checking with 17 new findings by adding functionality
  that checks for spaces around ternary operators using Perl.
*** *Ttyper* \hfill [[https://github.com/maxniederman/ttyper][ttyper]]
- Resolved one issue by implementing a functionality that permits to change the shape of the corners using Rust.
** *Education*
*** *Military Technical Academy*, Bucharest \hfill 2018 -- 2020
MA Telecommunications Engineering
*** *Military Technical Academy*, Bucharest \hfill 2014 -- 2018
BA Telecommunications Engineering
** *Other Skills*
Languages: Romanian, English, Italian, French
